package glfw.window;

import org.lwjgl.glfw.GLFW;

public enum WindowHint {

    FOCUSED(GLFW.GLFW_FOCUSED),
    ICONIFIED(GLFW.GLFW_ICONIFIED),
    RESIZABLE(GLFW.GLFW_RESIZABLE),
    VISIBLE(GLFW.GLFW_VISIBLE),
    DECORATED(GLFW.GLFW_DECORATED),
    AUTO_ICONIFY(GLFW.GLFW_AUTO_ICONIFY),
    FLOATING(GLFW.GLFW_FLOATING),
    MAXIMIZED(GLFW.GLFW_MAXIMIZED),
    CENTER_CURSOR(GLFW.GLFW_CENTER_CURSOR),
    TRANSPARENT_FRAMEBUFFER(GLFW.GLFW_TRANSPARENT_FRAMEBUFFER),
    HOVERED(GLFW.GLFW_HOVERED),
    FOCUS_ON_SHOW(GLFW.GLFW_FOCUS_ON_SHOW),

    CLIENT_API(GLFW.GLFW_CLIENT_API),
    CONTEXT_VERSION_MAJOR(GLFW.GLFW_CONTEXT_VERSION_MAJOR),
    CONTEXT_VERSION_MINOR(GLFW.GLFW_CONTEXT_VERSION_MINOR),
    CONTEXT_REVISION(GLFW.GLFW_CONTEXT_REVISION),
    CONTEXT_ROBUSTNESS(GLFW.GLFW_CONTEXT_ROBUSTNESS),
    OPENGL_FORWARD_COMPAT(GLFW.GLFW_OPENGL_FORWARD_COMPAT),
    OPENGL_DEBUG_CONTEXT(GLFW.GLFW_OPENGL_DEBUG_CONTEXT),
    OPENGL_PROFILE(GLFW.GLFW_OPENGL_PROFILE),
    CONTEXT_RELEASE_BEHAVIOR(GLFW.GLFW_CONTEXT_RELEASE_BEHAVIOR),
    CONTEXT_NO_ERROR(GLFW.GLFW_CONTEXT_NO_ERROR),
    CONTEXT_CREATION_API(GLFW.GLFW_CONTEXT_CREATION_API),
    SCALE_TO_MONITOR(GLFW.GLFW_SCALE_TO_MONITOR),
    ;

    private final int value;

    WindowHint(int value) {
        this.value = value;
    }

    public int get() {
        return value;
    }
}
